apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      hostname: {{ .Chart.Name | quote }}
      subdomain: {{ template "fullname" . }}
{{ include "imagePullSecrets" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
        env:
          - name: SCALITY_ACCESS_KEY_ID
            value: {{ .Values.key_id }}
          - name: SCALITY_SECRET_ACCESS_KEY
            value: {{ .Values.access_key }}
          - name: LOG_LEVEL
            value: {{ .Values.scality_loglevel }}
          # TODO: by setting host_name like that, we will be able to communicate with
          # aws server just by using http://{{ template "fullname" . }}:8000 url
          # using FQDN in it's place will not work. FQDN would need to registered
          # as an endpoint separately
          - name: HOST_NAME
            value: {{ template "fullname" . }}
        command:
         - "sh"
         - "-c"
         - >
           /usr/src/app/docker-entrypoint.sh npm start ;
        ports:
          - containerPort: 8000
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - >
                curl --output /dev/null --silent --connect-timeout 2 localhost:{{ .Values.scality_port }} ;
